openapi: 3.0.0
info:
  title: Realtime Chat API
  version: 1.0.0
  description: API documentation for the Realtime Chat Backend
paths:
  /api/chats:
    get:
      summary: Get all contacts for the authenticated user
      tags:
        - Contacts
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      $ref: '#/components/schemas/User'
                    latestMessage:
                      $ref: '#/components/schemas/Message'
        401:
          description: Unauthorized
        500:
          description: Server error
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        online:
          type: boolean
        socketIds:
          type: array
          items:
            type: string
          nullable: true
    Message:
      type: object
      properties:
        id:
          type: string
        sender:
          $ref: '#/components/schemas/User'
        receiver:
          $ref: '#/components/schemas/User'
        content:
          type: string
        seen:
          type: boolean
        createdAt:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
